#!/usr/bin/env bash
# Generate src/disk_image.h — a small read-only FAT12 image holding the host
# client files, embedded into the firmware and served over USB MSC. Run by the
# PlatformIO pre-build hook (tools/prebuild.py); can also be run by hand.
# Needs: dosfstools (mkfs.fat), mtools (mcopy), xxd.
set -euo pipefail
HERE="$(cd "$(dirname "$0")/.." && pwd)"
CLIENT="$HERE/../client"
OUT="$HERE/src/disk_image.h"
IMG="$(mktemp --suffix=.img)"
trap 'rm -f "$IMG"' EXIT

SIZE_KB=256
truncate -s "${SIZE_KB}K" "$IMG"
mkfs.fat -F 12 -n GEPPETTO "$IMG" >/dev/null

# A short pointer file so whoever plugs it in knows what to do.
READ_ME="$(mktemp)"
cat > "$READ_ME" <<'TXT'
Geppetto — host client
======================
This is one half of a Geppetto HID bridge: two soldered RP2040 Picos that
forward keyboard + mouse from this PC to another machine over a wire.

Setup (once): run the installer, then LOG OUT AND BACK IN:
    ./install.sh --autostart        # deps + groups + tray launcher/autostart

Run (no sudo once you're in the input/uucp groups):
    ./run_tray.sh                   # tray icon (recommended)
    ./run_gui.sh                    # settings window
    ./run.sh                        # client only

Double-tap RIGHT CTRL (default) to start/stop driving the other machine.
Full notes in the docstring at the top of geppetto.py, and at
https://github.com/Bake-Ware/geppetto
TXT

# The client needs geppetto_config.py; the GUI + tray are handy to carry too.
mcopy -i "$IMG" "$CLIENT/geppetto.py"        ::/geppetto.py
mcopy -i "$IMG" "$CLIENT/geppetto_config.py" ::/geppetto_config.py
mcopy -i "$IMG" "$CLIENT/geppetto_gui.py"    ::/geppetto_gui.py
mcopy -i "$IMG" "$CLIENT/geppetto_tray.py"   ::/geppetto_tray.py
mcopy -i "$IMG" "$CLIENT/run.sh"             ::/run.sh
mcopy -i "$IMG" "$CLIENT/run_gui.sh"         ::/run_gui.sh
mcopy -i "$IMG" "$CLIENT/run_tray.sh"        ::/run_tray.sh
mcopy -i "$IMG" "$CLIENT/install.sh"         ::/install.sh
mcopy -i "$IMG" "$CLIENT/install-desktop.sh" ::/install-desktop.sh
mcopy -i "$IMG" -s "$CLIENT/icons"           ::/icons
mcopy -i "$IMG" "$READ_ME"                   ::/README.txt
rm -f "$READ_ME"

{
    echo "// Auto-generated by tools/mkdisk.sh — DO NOT EDIT."
    echo "// Read-only FAT12 image (${SIZE_KB}K) of the host client, served over USB MSC."
    echo "#pragma once"
    echo "const unsigned char geppetto_disk[] = {"
    xxd -i < "$IMG"
    echo "};"
    echo "const unsigned long geppetto_disk_len = sizeof(geppetto_disk);"
} > "$OUT"

echo "mkdisk: wrote $OUT (image ${SIZE_KB}K = $((SIZE_KB*1024/512)) blocks)"
