#!/usr/bin/env bash
# Generate src/disk_image.h — a small read-only FAT12 image holding the host
# client files, embedded into the firmware and served over USB MSC. Run by the
# PlatformIO pre-build hook (tools/prebuild.py); can also be run by hand.
# Needs: dosfstools (mkfs.fat), mtools (mcopy), xxd.
set -euo pipefail
HERE="$(cd "$(dirname "$0")/.." && pwd)"
CLIENT="$HERE/../client"
OUT="$HERE/src/disk_image.h"
IMG="$(mktemp --suffix=.img)"
trap 'rm -f "$IMG"' EXIT

SIZE_KB=128
truncate -s "${SIZE_KB}K" "$IMG"
mkfs.fat -F 12 -n GEPPETTO "$IMG" >/dev/null

# A short pointer file so whoever plugs it in knows what to do.
READ_ME="$(mktemp)"
cat > "$READ_ME" <<'TXT'
Geppetto — host client
======================
This is one half of a Geppetto HID bridge: two soldered RP2040 Picos that
forward keyboard + mouse from this PC to another machine over a wire.

Run (needs root for /dev/input and the serial port):
    sudo python3 geppetto.py        # auto-detects the bridge port
Deps: pip install evdev pyserial

Double-tap RIGHT CTRL to start/stop driving the other machine.
Full notes in the docstring at the top of geppetto.py, and at
https://github.com/Bake-Ware/geppetto
TXT

mcopy -i "$IMG" "$CLIENT/geppetto.py" ::/geppetto.py
mcopy -i "$IMG" "$CLIENT/run.sh"      ::/run.sh
mcopy -i "$IMG" "$READ_ME"            ::/README.txt
rm -f "$READ_ME"

{
    echo "// Auto-generated by tools/mkdisk.sh — DO NOT EDIT."
    echo "// Read-only FAT12 image (${SIZE_KB}K) of the host client, served over USB MSC."
    echo "#pragma once"
    echo "const unsigned char geppetto_disk[] = {"
    xxd -i < "$IMG"
    echo "};"
    echo "const unsigned long geppetto_disk_len = sizeof(geppetto_disk);"
} > "$OUT"

echo "mkdisk: wrote $OUT (image ${SIZE_KB}K = $((SIZE_KB*1024/512)) blocks)"
